#docker build && docker run
services:
 # mysql:
  #  image: mysql:8.0
   # container_name: mysql
    #environment:
     # MYSQL_ROOT_PASSWORD: Test@123
      #MYSQL_DATABASE: bankappdb
    #healthcheck:
     # test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-pTest@123"]
      #interval: 10s
      #timeout: 5s
      #retries: 3
      #start_period: 30s
    #ports:
     # - "3306:3306"
    #volumes:
    #  - mysql-data:/var/lib/mysql
    #networks:
     # - bankapp-nw
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    # 🌟 ADD THIS COMMAND LINE: Forcefully shrinks memory footprints so it runs on 1GB RAM servers
    command: --innodb-buffer-pool-size=64M --innodb-log-buffer-size=16M --max-connections=10
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
      # 🌟 ADD THIS LINE: Allows root access from any container on the docker network mesh
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp-nw

  bankapp:
    image: ${DOCKERHUB_USERNAME}/ai-bank-app:${DOCKER_TAG}
    container_name: bankapp
    ports:
        - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: bankappdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123
      OLLAMA_URL: http://ollama:11434
    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - bankapp-nw

  ollama:
    # 🌟 Pulling version 0.1.48 bypasses the heavy multi-gigabyte CUDA layers completely!
    image: ollama/ollama:0.1.48
    container_name: ollama
    ports:
    - "11434:11434"
    networks:
      - bankapp-nw
    volumes:
      - ollama_data:/root/.ollama

#docker network create
networks:
  bankapp-nw:
    driver: bridge

#docker volume create 
volumes:
  mysql-data:
  ollama_data: