kind: PersistentVolume
apiVersion: v1
metadata:
  name: ollama-pv
  labels:
    app: ollama
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ollama

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
  namespace: bankapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: ollama

