# Linting scan - Checkstyle
# SAST scan - SpotBugs

name: Code-scan

on:
  
    workflow_call:

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                java-version: ['21']

        steps:

            - name: checkout code
              uses: actions/checkout@v4

             # 🌟 PASTE THE CLEANUP TASK DIRECTLY HERE 🌟
            - name: Free Disk Space on Runner Computer
              run: |
                echo "Reclaiming local storage space on GitHub runner..."
                sudo rm -rf /usr/share/dotnet
                sudo rm -rf /usr/local/lib/android
                sudo rm -rf /opt/ghc
                sudo rm -rf "/usr/local/share/boost"


            - name: setup java ${{ matrix.java-version }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ matrix.java-version }}
                distribution: 'temurin'
                cache: 'maven'

            - name: run linter Checkstyle
              run: ./mvnw checkstyle:check || echo "Linting Completed"

            - name: run SAST (SpotBugs & Security scan)
              run: |
                ./mvnw compile com.github.spotbugs:spotbugs-maven-plugin:4.8.2.0:spotbugs || echo "SAST completed"
