# Linting scan - Checkstyle
# SAST scan - SpotBugs

name: Code-scan

on:
  
    workflow_call:

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                java-version: ['21']

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: setup java ${{ matrix.java-version }}
              uses: actions/setup-java@v4
              with:
                java-version: ${{ matrix.java-version }}
                distribution: 'temurin'
                cache: 'maven'

            - name: run linter Checkstyle
              run: ./mvnw checkstyle:check || echo "Linting Completed"

            - name: run SAST (SpotBugs & Security scan)
              run: |
                ./mvnw compile com.github.spotbugs:spotbugs-maven-plugin:4.8.2.0:spotbugs || echo "SAST completed"
